version: "3.9"
services:
  frontend:
    container_name: frontend
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.local
    restart: always
    env_file: ./apps/frontend/.env
    ports:
      - 5173:5173
    depends_on:
      - backend
    volumes:
      - "./apps/frontend/src:/usr/src/app/src"
    networks:
      - bp-network
    command: "pnpm run dev"
  
  backend:
    container_name: backend
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.local
    restart: always
    env_file: ./apps/backend/.env
    volumes:
      - ./apps/backend:/svr/app
      - "./scripts/wait.sh:/wait.sh"
      - /svr/app/node_modules
    networks:
      - bp-network
    ports:
      - 5000:5000

networks:
  bp-network:
    driver: bridge
