FROM node:20-slim as build

RUN npm install pnpm -g

WORKDIR /app
COPY package.json .

RUN pnpm install

COPY . .

RUN npm run build

FROM nginx:alpine
COPY nginx.config /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
