name: Build and Push Docker Images

on:
  push:
    paths:
      - "apps/frontend/**"
      - "apps/backend/**"
      - ".github/workflows/docker-build.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REPO: your-dockerhub-username/your-repo-name

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build and push the frontend image
      - name: Build and Push Frontend
        if: ${{ github.event.paths.* contains 'apps/frontend/' }}
        run: |
          docker build -f apps/frontend/Dockerfile.local -t $DOCKER_REPO:frontend-latest ./apps/frontend
          docker push $DOCKER_REPO:frontend-latest

      # Build and push the backend image
      - name: Build and Push Backend
        if: ${{ github.event.paths.* contains 'apps/backend/' }}
        run: |
          docker build -f apps/backend/Dockerfile.local -t $DOCKER_REPO:backend-latest ./apps/backend
          docker push $DOCKER_REPO:backend-latest
